[package]
name = "todoproxy-api"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
derive_more = { version="1.0.0", features=["full"]}
num-traits = "0.2.19"
num-derive = "0.4.2"
serde_json = "1.0.127"
