[package]
name = "todoproxy-api"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
derive_more = "0.99.17"
num-traits = "0.2.18"
num-derive = "0.4.2"
serde_json = "1.0.116"
